theme: jekyll-theme-dinky
title: David B Dean
linkedin_url: https://linkedin.com/in/davidbdean
resume_url: /assets/David%20Dean%20Resume%202017.pdf
email: ddean@ieee.org
scholar_url: https://scholar.google.com.au/citations?user=RG75LQYAAAAJ
